"""Add game_user Association Table

Revision ID: 06e617c47964
Revises: 2fdbb5c422ce
Create Date: 2024-12-15 03:47:38.854960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e617c47964'
down_revision = '2fdbb5c422ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
