"""Add User model

Revision ID: 2fdbb5c422ce
Revises: 675b8401af9c
Create Date: 2024-12-15 03:17:46.263369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdbb5c422ce'
down_revision = '675b8401af9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
